### ISSUE TITLE
long and short description for a project?

### ISSUE THREAD

**Issue by justincy** [treehub-eng/firebase-rules#9]
Do we want both a long and short description? The current firebase rules only include one but the design mocks show two.

**Comment by jonnymbgood** [comment]
@justincy Two would probably be better. Any name recommendations for the shorter one? tagline?

**Comment by justincy** [comment]
tagline works for me.

**Comment by jonnymbgood** [comment]
We should probably limit the length. How many characters should we allow?

**Comment by justincy** [comment]
100 seems fine.
